name: pipeline
trigger:
- main

pool: Agent007

stages:
  - stage: dependencies 
    displayName: 'Install Dependencies'
    jobs:
    - job: install
      steps:
      - bash: |
        sudo apt-get install terraform

  - stage: terraform steps
    displayName: 'Do Terraform Steps'
    jobs:
    - job: steps
      steps:
      - bash: |
        terraform init
        terraform plan
        terraform apply

#verandering