trigger:
- new

pool:
  name: Agent007

#variables:
#  subscriptionId: 'f82b3c62-b635-402b-afa2-a1a807bbfd42'
  
stages:
- stage: tfvalidate 
  jobs:
  - job: validate
    steps:

    - script: | 
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK'
      inputs:
        packageType: 'sdk'
        version: '3.1.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: TerraformInstaller@0
      displayName: tfinstall
      inputs:
        terraformVersion: 'latest'

    - script: |
        az login --identity

    - script: |
        az account show
        terraform init -backend=false
        
    - script: |
        terraform validate

- stage: tfdeploy
  condition: succeeded('tfvalidate')
  dependsOn: tfvalidate
  jobs:
  - job: apply
    steps:

    - task: TerraformInstaller@0
      displayName: tfinstall
      inputs:
        terraformVersion: 'latest'

    - script: |
        az login --identity

    - script: |
        az account show
        terraform init -backend=false

    - script: |
        terraform plan -out=tfplan

    - script: |
        terraform apply tfplan