trigger:
- new

pool:
  name: Agent007

variables:
  azureSubscriptionEndpoint: 'matthijsconnection'
  
stages:
- stage: tfvalidate 
  jobs:
  - job: validate
    steps:

    - script: | 
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az login

    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK'
      inputs:
        packageType: 'sdk'
        version: '3.1.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: TerraformInstaller@0
      displayName: tfinstall
      inputs:
        terraformVersion: 'latest'

    - script: |
        az account set --subscription $(azureSubscriptionEndpoint)
      
    - script: |
        terraform init -backend=false
        
    - script: |
        terraform validate

- stage: tfdeploy
  condition: succeeded('tfvalidate')
  dependsOn: tfvalidate
  jobs:
  - job: apply
    steps:

    - task: TerraformInstaller@0
      displayName: tfinstall
      inputs:
        terraformVersion: 'latest'

    - script: |
        az account set --subscription $(azureSubscriptionEndpoint)

    - script: |
        terraform init -backend=false

    - script: |
        terraform plan -out=tfplan

    - script: |
        terraform apply tfplan
