trigger:
- new

pool:
  name: Agent007

variables:
  subscriptionId: '41e50375-b926-4bc4-9045-348f359cf721'
  terraformPath: '/home/agent/_work/1/s'
  
stages:
- stage: tfvalidate 
  jobs:
  - job: validate
    steps:
    - script: | 
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - script: |
        az login --identity --allow-no-subscriptions
        az account set --subscription $(subscriptionId)
        az account show
        cd $(System.DefaultWorkingDirectory) && ls
        terraform init

    - script: |
        terraform validate

- stage: tfdeploy
  condition: succeeded('tfvalidate')
  dependsOn: tfvalidate
  jobs:
  - job: apply
    steps:
    - script: |
        az login --identity --allow-no-subscriptions
        az account set --subscription $(subscriptionId)
        az account show
        cd $(System.DefaultWorkingDirectory) && ls
        terraform init

    - script: |
        terraform plan -out=tfplan -input=false -var-file=$(System.DefaultWorkingDirectory)/path/to/your/variables.tfvars

    - script: |
        terraform apply -input=false -auto-approve tfplan