trigger:
- new

pool:
  name: Agent007

variables:
  subscriptionId: '41e50375-b926-4bc4-9045-348f359cf721'
  
stages:
- stage: tfvalidate 
  jobs:
  - job: validate
    steps:

    - script: | 
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - task: TerraformInstaller@0
      displayName: tfinstall
      inputs:
        terraformVersion: 'latest'
        workingDirectory: '$(System.DefaultWorkingDirectory)/$(terraformPath)/'

    - script: |
        az login --identity --allow-no-subscriptions
        az account set --subscription $(subscriptionId)
        az account show
        cd $(System.DefaultWorkingDirectory) && ls
        terraform -chdir=$(System.DefaultWorkingDirectory) init
        
    - script: |
        terraform validate

- stage: tfdeploy
  condition: succeeded('tfvalidate')
  dependsOn: tfvalidate
  jobs:
  - job: apply
    steps:

    - task: TerraformInstaller@0
      displayName: tfinstall
      inputs:
        terraformVersion: 'latest'
        workingDirectory: '$(System.DefaultWorkingDirectory)/$(terraformPath)/'

    - script: |
        az login --identity --allow-no-subscriptions
        az account set --subscription $(subscriptionId)
        az account show
        cd $(System.DefaultWorkingDirectory) && ls
        terraform -chdir=$(System.DefaultWorkingDirectory) init

    - script: |
        cd $(System.DefaultWorkingDirectory) && ls
        terraform -chdir=$(System.DefaultWorkingDirectory) plan

#    - script: |
#        cd $(System.DefaultWorkingDirectory) && ls
#        terraform -chdir=$(System.DefaultWorkingDirectory) apply

    - task: TerraformTaskV2@2
      displayName: 'Terraform Apply'
      condition: and(succeeded(), not(eq(variables.storageAccountName, '')), not(eq(variables.storageAccountKey, '')))
      enabled: true
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: '-input=false -auto-approve -var="ssh_public_key=$(sshPublicKey)" -var="location=$(location)" -var="resource_group_name=$(resourceGroupName)" -var="script_storage_account_name=$(storageAccountName)" -var="script_storage_account_key=$(storageAccountKey)" -var="container_name=$(containerName)" -var="script_name=$(scriptName)" -var="kubernetes_version=$(kubernetesVersion)" -var-file="$(System.DefaultWorkingDirectory)/tfvars/$(environment)/$(environment).tfvars"'
#        environmentServiceNameAzureRM: $(azureSubscription)
        workingDirectory: '$(System.DefaultWorkingDirectory)/$(terraformPath)/'