trigger:
- new

pool:
  name: Agent007

variables:
  subscriptionId: '41e50375-b926-4bc4-9045-348f359cf721'
  
stages:
- stage: tfvalidate 
  jobs:
  - job: validate
    steps:

    - script: | 
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - task: TerraformInstaller@0
      displayName: tfinstall
      inputs:
        terraformVersion: 'latest'

    - script: |
        az login --identity --subscription $(subscriptionId)
        az account show
        terraform init
        
    - script: |
        terraform validate

- stage: tfdeploy
  condition: succeeded('tfvalidate')
  dependsOn: tfvalidate
  jobs:
  - job: apply
    steps:

    - task: TerraformInstaller@0
      displayName: tfinstall
      inputs:
        terraformVersion: 'latest'

    - script: |
        az login --identity --subscription $(subscriptionId)
        az account show
        terraform init

    - script: |
        terraform plan

    - script: |
        terraform apply