trigger:
- new

pool:
  name: Agent007

variables:
  subscriptionId: '41e50375-b926-4bc4-9045-348f359cf721'
  terraformPath: /usr/bin/bash --noprofile --norc /home/agent/_work/_temp/44115a1e-e440-4135-82d4-50fa476e8d66.sh
  terraform_folder_name: /home/matthijssliggers/pro5/devoteam-traineeship-petclinic/terraform
  
stages:
- stage: tfvalidate 
  jobs:
  - job: validate
    steps:

    - script: | 
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - task: TerraformInstaller@0
      displayName: tfinstall
      inputs:
        terraformVersion: 'latest'
        workingDirectory: '$(System.DefaultWorkingDirectory)/$(terraformPath)/'

    - script: |
        az login --identity --allow-no-subscriptions
        az account set --subscription $(subscriptionId)
        az account show
        cd $(System.DefaultWorkingDirectory)$(terraform_folder_name)
        terraform -chdir=$(System.DefaultWorkingDirectory) init
        
    - script: |
        terraform validate

- stage: tfdeploy
  condition: succeeded('tfvalidate')
  dependsOn: tfvalidate
  jobs:
  - job: apply
    steps:

    - task: TerraformInstaller@0
      displayName: tfinstall
      inputs:
        terraformVersion: 'latest'
        workingDirectory: '$(System.DefaultWorkingDirectory)/$(terraformPath)/'

    - script: |
        az login --identity --allow-no-subscriptions
        az account set --subscription $(subscriptionId)
        az account show
        cd $(System.DefaultWorkingDirectory) && ls
        terraform -chdir=$(System.DefaultWorkingDirectory) init

    - script: |
        cd $(System.DefaultWorkingDirectory) && ls
        terraform -chdir=$(System.DefaultWorkingDirectory) plan

    - script: |
        cd $(System.DefaultWorkingDirectory) && ls
        terraform -chdir=$(System.DefaultWorkingDirectory) apply